// packages/plugins/typescript/solid-urql/src/visitor.ts
import {
  ClientSideBaseVisitor,
  ClientSideBasePluginConfig,
  LoadedFragment,
  DocumentMode,
  RawClientSideBasePluginConfig,
} from "@graphql-codegen/visitor-plugin-common";
import { GraphQLSchema, OperationDefinitionNode, Kind } from "graphql";
import { SolidUrqlPluginConfig } from "./config";

export interface SolidUrqlPluginRawConfig
  extends RawClientSideBasePluginConfig {
  withPrimitives?: boolean;
  urqlImportFrom?: string;
}

export class SolidUrqlVisitor extends ClientSideBaseVisitor<
  SolidUrqlPluginRawConfig,
  SolidUrqlPluginConfig
> {
  private _externalImportPrefix: string;

  constructor(
    schema: GraphQLSchema,
    fragments: LoadedFragment[],
    rawConfig: SolidUrqlPluginRawConfig,
    documents: any[],
  ) {
    super(schema, fragments, rawConfig, {
      withPrimitives: rawConfig.withPrimitives !== false,
      urqlImportFrom: rawConfig.urqlImportFrom || "solid-urql",
      documentMode: DocumentMode.string,
    } as any);

    this._externalImportPrefix = this.config.importOperationTypesFrom
      ? `${this.config.importOperationTypesFrom}.`
      : "";
  }

  public getImports(): string[] {
    const baseImports = super.getImports();
    const imports: string[] = [...baseImports];

    if (this.config.withPrimitives) {
      imports.push(
        `import { createQuery, createMutation, type CreateQueryArgs, type CreateMutationState } from '${this.config.urqlImportFrom}';`,
      );
    }

    imports.push(`import type { Accessor } from 'solid-js';`);
    imports.push(
      `import type { OperationContext, OperationResult } from '@urql/core';`,
    );

    return imports.filter(Boolean);
  }

  protected buildOperation(
    node: OperationDefinitionNode,
    documentVariableName: string,
    operationType: string,
    operationResultType: string,
    operationVariablesTypes: string,
    hasRequiredVariables: boolean,
  ): string {
    const operationName = this.convertName(node.name?.value || "", {
      useTypesPrefix: false,
      useTypesSuffix: false,
    });

    if (!this.config.withPrimitives) {
      return "";
    }

    if (operationType === "Query") {
      return this.buildQueryHook(
        node,
        operationName,
        documentVariableName,
        operationResultType,
        operationVariablesTypes,
        hasRequiredVariables,
      );
    } else if (operationType === "Mutation") {
      return this.buildMutationHook(
        node,
        operationName,
        documentVariableName,
        operationResultType,
        operationVariablesTypes,
        hasRequiredVariables,
      );
    } else if (operationType === "Subscription") {
      return this.buildSubscriptionHook(
        node,
        operationName,
        documentVariableName,
        operationResultType,
        operationVariablesTypes,
        hasRequiredVariables,
      );
    }

    return "";
  }

  private buildQueryHook(
    node: OperationDefinitionNode,
    operationName: string,
    documentVariableName: string,
    operationResultType: string,
    operationVariablesTypes: string,
    hasRequiredVariables: boolean,
  ): string {
    const hookName = `useCreate${operationName}`;

    const argsType = hasRequiredVariables
      ? `Omit<CreateQueryArgs<${operationVariablesTypes}, ${operationResultType}>, 'query'>`
      : `Omit<CreateQueryArgs<${operationVariablesTypes}, ${operationResultType}>, 'query'> = {}`;

    return `
export const ${hookName} = (args: ${argsType}) => {
  return createQuery<${operationResultType}, ${operationVariablesTypes}>({
    ...args,
    query: ${documentVariableName},
  });
};
`;
  }

  private buildMutationHook(
    node: OperationDefinitionNode,
    operationName: string,
    documentVariableName: string,
    operationResultType: string,
    operationVariablesTypes: string,
    hasRequiredVariables: boolean,
  ): string {
    const hookName = `useCreate${operationName}`;

    return `
export const ${hookName} = () => {
  return createMutation<${operationResultType}, ${operationVariablesTypes}>(${documentVariableName});
};
`;
  }

  private buildSubscriptionHook(
    node: OperationDefinitionNode,
    operationName: string,
    documentVariableName: string,
    operationResultType: string,
    operationVariablesTypes: string,
    hasRequiredVariables: boolean,
  ): string {
    const hookName = `useCreate${operationName}`;

    const argsType = hasRequiredVariables
      ? `Omit<CreateQueryArgs<${operationVariablesTypes}, ${operationResultType}>, 'query'>`
      : `Omit<CreateQueryArgs<${operationVariablesTypes}, ${operationResultType}>, 'query'> = {}`;

    return `
export const ${hookName} = (args: ${argsType}) => {
  return createSubscription<${operationResultType}, ${operationVariablesTypes}>({
    ...args,
    query: ${documentVariableName},
  });
};
`;
  }
}

// packages/plugins/typescript/react-apollo-offix/src/visitor.ts
import autoBind from 'auto-bind';
import { pascalCase } from 'change-case-all';
import { GraphQLSchema, OperationDefinitionNode } from 'graphql';
import { Types } from '@graphql-codegen/plugin-helpers';
import {
  ClientSideBasePluginConfig,
  ClientSideBaseVisitor,
  DocumentMode,
  LoadedFragment,
  RawClientSideBasePluginConfig,
} from '@graphql-codegen/visitor-plugin-common';

export interface ReactApolloPluginConfig extends ClientSideBasePluginConfig {}

export class ReactApolloVisitor extends ClientSideBaseVisitor<
  RawClientSideBasePluginConfig,
  ReactApolloPluginConfig
> {
  private _externalImportPrefix: string;
  private imports = new Set<string>();

  constructor(
    schema: GraphQLSchema,
    fragments: LoadedFragment[],
    rawConfig: RawClientSideBasePluginConfig,
    documents: Types.DocumentFile[],
  ) {
    super(schema, fragments, rawConfig, {});

    this._externalImportPrefix = this.config.importOperationTypesFrom
      ? `${this.config.importOperationTypesFrom}.`
      : '';
    this._documents = documents;

    autoBind(this);
  }

  private getOffixReactHooksImport(): string {
    return `import * as OffixReactHooks from "react-offix-hooks";`;
  }

  private getDocumentNodeVariable(
    node: OperationDefinitionNode,
    documentVariableName: string,
  ): string {
    return this.config.documentMode === DocumentMode.external
      ? `Operations.${node.name.value}`
      : documentVariableName;
  }

  public getImports(): string[] {
    const baseImports = super.getImports({ excludeFragments: true });
    const hasOperations = this._collectedOperations.length > 0;

    if (!hasOperations) {
      return baseImports;
    }

    return [...baseImports, ...Array.from(this.imports)];
  }

  private _buildHooks(
    node: OperationDefinitionNode,
    operationType: string,
    documentVariableName: string,
    operationResultType: string,
    operationVariablesTypes: string,
  ): string {
    const operationName: string = this.convertName(node.name?.value ?? '', {
      useTypesPrefix: false,
    });

    this.imports.add(this.getOffixReactHooksImport());

    const hookFns = [];

    if (operationType === 'Mutation') {
      hookFns.push(
        `export function useOffline${operationName}(baseOptions?: OffixReactHooks.${operationType}HookOptions<${operationResultType}, ${operationVariablesTypes}>) {
    return OffixReactHooks.useOfflineMutation<${operationResultType}, ${operationVariablesTypes}>(${this.getDocumentNodeVariable(
          node,
          documentVariableName,
        )}, baseOptions);
}`,
      );
    }

    return [...hookFns].join('\n');
  }

  protected buildOperation(
    node: OperationDefinitionNode,
    documentVariableName: string,
    operationType: string,
    operationResultType: string,
    operationVariablesTypes: string,
  ): string {
    operationResultType = this._externalImportPrefix + operationResultType;
    operationVariablesTypes = this._externalImportPrefix + operationVariablesTypes;

    const hooks = this._buildHooks(
      node,
      operationType,
      documentVariableName,
      operationResultType,
      operationVariablesTypes,
    );

    return [hooks].filter(a => a).join('\n');
  }

  OperationDefinition(node: OperationDefinitionNode) {
    if (!node.name || !node.name.value) {
      return null;
    }
    this._collectedOperations.push(node);
    const documentVariableName = this.convertName(node, {
      suffix: this.config.documentVariableSuffix,
      prefix: this.config.documentVariablePrefix,
      useTypesPrefix: false,
    });

    const operationType = pascalCase(node.operation);
    const operationTypeSuffix = this.getOperationSuffix(node, operationType);
    const operationResultType = this.convertName(node, {
      suffix: operationTypeSuffix + this._parsedConfig.operationResultSuffix,
    });
    const operationVariablesTypes = this.convertName(node, {
      suffix: operationTypeSuffix + 'Variables',
    });
    const additional = this.buildOperation(
      node,
      documentVariableName,
      operationType,
      operationResultType,
      operationVariablesTypes,
    );
    return [additional].filter(a => a).join('\n');
  }
}
